config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  root 'logins#new'

  resources :admins, except: :show

  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'

  get 'map', to: 'map#display'

  resources :tokens, except: :show

  resources :upload, except: :show
  get '/upload/make_current_map/:id' => 'upload#make_current_map', as: :make_current_map
  get '/upload/corridor/new/:id' => 'upload#new_corridor', as: :new_corridor
  patch '/upload/corridor/:id' => 'upload#upload_corridor', as: :upload_corridor

  resources :classrooms

  namespace :api, defaults: {format: :json} do

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      resources :map, only: [:index, :create]
      get 'map2', to: 'map#map2'

      resources :classrooms, only: [:index, :show]
      get '/classroom/:name', to: 'classrooms#show_by_name'
      get '/classroom_search/:query', to: 'classrooms#search_by_name'

      get '/tags/:id', to: 'tags#get_tags'
      post '/tags/:id', to: 'tags#save_for_classroom'
      delete '/tags/:id', to: 'tags#delete_tag'

      resources :corridors, only: :index
      get '/corridors2', to: 'corridors#corridors2'
      resources :stairs, only: :index
      get '/stair/:name', to: 'stairs#show_by_name'

      get :path, to: 'path#find'

      get :docs, to: 'docs#index'

    end

  end

end

app/views/admins/_form.html.erb
<%= render 'shared/errors', obj: @admin %>

<div class="card-panel hoverable">
  <div class="row">
    <div class="col s12">

      <%= form_for(@admin) do |f| %>
          <div class="row">
            <div class="input-field col s6 offset-s3">
              <%= f.text_field :username, class: 'validate', autofocus: true %>
              <label>Nom d'utilisateur</label>
            </div>
          </div>

          <div class="row">
            <div class="input-field col s6 offset-s3">
              <%= f.password_field :password, class: 'validate' %>
              <label>Mot de passe</label>
            </div>
          </div>

          <div class="row">
            <div class="input-field col s6 offset-s3">
              <%= f.text_field :email, class: 'validate' %>
              <label>Courriel</label>
            </div>
          </div>

          <div class="row">
            <div class="col s6 offset-s3">
              <%= f.check_box :master_admin, id: 'master-admin' %>
              <label for="master-admin">Administrateur maître</label>
            </div>
          </div>

          <div class="col s6 offset-s3">
            <%= link_to 'Revenir', admins_path, class: 'btn waves-effect waves-light red' %>
            <%= f.submit (@admin.new_record? ? 'Créer' : 'Modifier'), class: 'btn waves-effect waves-light' %>
          </div>

      <% end %>

    </div>
  </div>
</div>

app/views/admins/edit.html.erb
<div class="container">
  <h1 class="center-align thin">Modifier l'administrateur</h1>
  <%= render 'form' %>
</div>

app/views/admins/index.html.erb
<div class="row">

  <div class="col s12 m4 l3 fixed-control">

    <div class="card card-top">
      <div class="card-content">
        <span class="card-title thin">Administrateurs</span>
        <p>Voici tous les administrateurs. On peut les modifier ou les supprimer.</p>
      </div>
      <div class="card-action">
        <% if current_admin && current_admin.master_admin? %>
            <%= link_to raw('<i class="material-icons right">add</i>Nouvel administrateur'), new_admin_path, class: 'btn waves-effect waves-light' %>
        <% end %>

      </div>
    </div>

    <div class="side-card">
      <ul class="collapsible" data-collapsible="expandable">
        <li>
          <div class="collapsible-header">
            <span class="badge"><%= @admins.count %></span><i class="material-icons">place</i>Administrateurs
          </div>
          <div class="collapsible-body"><p>Lorem ipsum dolor sit amet.</p></div>
        </li>
      </ul>
    </div>
  </div>
  <div class="col s12 m8 l9 offset-m4 offset-l3">
    <div class="card card-top">
      <div class="card-content no-padding">
        <table class="centered">
          <thead>
          <tr>
            <th>Nom d'utilisateur</th>
            <th>Adresse courriel</th>
            <th>Administrateur maître</th>
            <th width="20%">Actions</th>
          </tr>
          </thead>

          <tbody>
          <% @admins.each do |admin| %>
              <tr class="table-action table-row">
                <td><%= admin.username %></td>
                <td><%= admin.email %></td>
                <td><%= admin.master_admin ? 'Oui' : 'Non' %></td>
                <td>
                  <% if current_admin && current_admin.master_admin? || admin == current_admin %>
                      <%= link_to raw('<i class="material-icons">edit</i>'), edit_admin_path(admin), class: 'btn btn-floating waves-effect waves-light waves-circle blue' %>
                  <% end %>
                  <% if current_admin && current_admin.master_admin? %>
                      <%= link_to raw('<i class="material-icons">delete</i>'), admin, method: :delete, data: {confirm: 'Êtes vous certain de vouloir supprimer cette administrateur ?'}, class: 'btn btn-floating waves-effect waves-light red' %>
                  <% end %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

app/views/admins/new.html.erb
<div class="container">
  <h1 class="center-align thin">Nouvel administrateur</h1>
  <%= render 'form' %>
</div>