config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  root 'logins#new'

  resources :admins, except: :show

  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'

  get 'map', to: 'map#display'

  resources :tokens, except: :show

  resources :upload, except: :show
  get '/upload/make_current_map/:id' => 'upload#make_current_map', as: :make_current_map
  get '/upload/corridor/new/:id' => 'upload#new_corridor', as: :new_corridor
  patch '/upload/corridor/:id' => 'upload#upload_corridor', as: :upload_corridor

  resources :classrooms

  namespace :api, defaults: {format: :json} do

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      resources :map, only: [:index, :create]
      get 'map2', to: 'map#map2'

      resources :classrooms, only: [:index, :show]
      get '/classroom/:name', to: 'classrooms#show_by_name'
      get '/classroom_search/:query', to: 'classrooms#search_by_name'

      get '/tags/:id', to: 'tags#get_tags'
      post '/tags/:id', to: 'tags#save_for_classroom'
      delete '/tags/:id', to: 'tags#delete_tag'

      resources :corridors, only: :index
      get '/corridors2', to: 'corridors#corridors2'
      resources :stairs, only: :index
      get '/stair/:name', to: 'stairs#show_by_name'

      get :path, to: 'path#find'

      get :docs, to: 'docs#index'

    end

  end

end

app/controllers/upload_controller.rb
class UploadController < ApplicationController
  before_action :require_admin
  before_action :get_map, only: [:edit, :update, :destroy, :make_current_map, :upload_corridor, :new_corridor]

  # GET /upload

  def index
    @maps = Map.all
  end

  # POST /upload

  def create
    @map = Map.new(map_params)
    if @map.save
      flash[:success] = "La carte a été téléversée avec succès."
      redirect_to upload_index_path
    else
      render 'new'
    end
  end

  # PUT PATCH /upload/:id

  def update
    if @map.update(map_params)
      flash[:success] = "La carte a été mise à jour avec succès."
      redirect_to upload_index_path
    else
      render 'edit'
    end
  end

  # DELETE /upload/:id

  def destroy
    key_name = @map.name
    @map.destroy
    flash[:danger] = "#{key_name} a bien été supprimer."
    redirect_to upload_index_path
  end


  # GET /upload/new

  def new
    @map = Map.new
  end

  # GET /upload/:id/edit

  def edit
  end

  def make_current_map
    if @map.currentMap
      map_url = @map.map.url

      map_json = parse('public' + map_url)
      feed_db(map_json)

      @map.update({currentMap: false})
      flash[:success] = "La carte #{@map.name} a été désactivé pour l'étage #{@map.floor}."
      redirect_to upload_index_path
    elsif @map.corridor.present?
      @map.update({currentMap: true})
      flash[:success] = "La carte #{@map.name} a bien été activé pour l'étage #{@map.floor}."
      redirect_to upload_index_path
    else
      flash[:danger] = "La carte #{@map.name} ne peut être activé sans la carte des corridors."
      redirect_to upload_index_path
    end
  end

  def new_corridor
  end

  def upload_corridor
    @map.corridor = params[:map][:corridor]
    @map.save!
    redirect_to upload_index_path
  end

  private
  def map_params
    params.require(:map).permit(:map, :name, :floor, :corridor)
  end

  def get_map
    @map = Map.find(params[:id])
  end

end

app/views/upload/_form.html.erb
<%= render 'shared/errors', obj: @map %>

<div class="card-panel hoverable">
  <div class="row">
    <div class="col s12">
      <%= form_for(@map, url: upload_index_path(@map), :html => {class: 'col s12'}) do |f| %>

          <div class="row">
            <div class="input-field col s9">
              <%= f.text_field :name, class: 'validate', autofocus: true %>
              <label>Nom</label>
            </div>

            <div class="input-field col s3">
              <%= f.number_field :floor, class: 'validate' %>
              <label>Étage</label>
            </div>
          </div>

          <div class="row">
            <div class="col s12">
              <div class="file-field input-field">
                <div class="btn waves-effect waves-light"><span>Fichier des locaux</span><%= f.file_field :map %></div>
                <div class="file-path-wrapper"><input class="file-path validate" type="text"></div>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col s12">
              <div class="file-field input-field">
                <div class="btn waves-effect waves-light"><span>Fichier des corridors</span><%= f.file_field :corridor %></div>
                <div class="file-path-wrapper"><input class="file-path validate" type="text"></div>
              </div>
            </div>
          </div>

          <%= link_to 'Annuler', upload_index_path, class: 'btn waves-effect waves-light red' %>
          <%= f.submit ('Téléverser'), class: 'btn waves-effect waves-light' %>

      <% end %>
    </div>
  </div>
</div>

app/views/upload/edit.html.erb
<div class="container">
  <h1 class="center-align thin">Modifier la carte</h1>

  <%= render 'shared/errors', obj: @map %>

  <div class="card-panel hoverable">
    <div class="row">
      <div class="col s12">
        <%= form_for(@map, url: upload_path(@map), method: :patch, :html => {class: 'col s12'}) do |f| %>

            <div class="row">
              <div class="input-field col s9">
                <%= f.text_field :name, autofocus: true %>
                <label>Nom</label>
              </div>

              <div class="input-field col s3">
                <%= f.number_field :floor %>
                <label>Étage</label>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.check_box :currentMap, id: 'current-map' %>
                <label for="current-map">Carte actuelle</label>
              </div>
            </div>

            <%= link_to 'Annuler', upload_index_path, class: 'btn waves-effect waves-light red' %>
            <%= f.submit ('Mettre à jour'), class: 'btn waves-effect waves-light' %>

        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/upload/index.html.erb
<div class="row">
  <div class="col s12 m4 l3 fixed-control">
    <div class="card card-top">
      <div class="card-content">
        <span class="card-title thin">Gestion des cartes</span>
        <p>Voici tous les cartes du cégep. On peut les modifier ou les supprimer.</p>
      </div>
      <div class="card-action">
        <%= link_to raw('<i class="material-icons right">add</i>Téléverser une carte'), new_upload_path, class: 'btn waves-effect waves-light' %>
      </div>
    </div>

    <div class="side-card">
      <ul class="collapsible" data-collapsible="expandable">
        <li>
          <div class="collapsible-header">
            <span class="badge"><%= @maps.count %></span><i class="material-icons">place</i>cartes
          </div>
        </li>
      </ul>
    </div>

  </div>
  <div class="col s12 m8 l9 offset-m4 offset-l3">
    <div class="card card-top">
      <div class="card-content no-padding">
        <table class="centered">
          <thead>
          <tr>
            <th>Nom</th>
            <th>Étage</th>
            <th>Corridor téléverser</th>
            <th>Carte actuelle</th>
            <th></th>
            <th>Actions</th>
          </tr>
          </thead>

          <tbody>
          <% @maps.each do |map| %>
              <tr class="table-action table-row">
                <td><%= map.name %></td>
                <td width="10%"><%= map.floor %></td>
                <td width="15%"><%= map.corridor.present? ? 'Oui' : 'Non' %></td>
                <td width="15%"><%= map.currentMap ? 'Oui' : 'Non' %></td>
                <td width="17%"><%= link_to (map.currentMap ? 'Désactiver' : 'Activer'), make_current_map_path(map), class: 'btn' %></td>
                <td width="15%">
                  <%= link_to raw('<i class="material-icons">edit</i>'), edit_upload_path(map), class: 'btn btn-floating waves-effect waves-light waves-circle blue' %>
                  <%= link_to raw('<i class="material-icons">delete</i>'), upload_path(map), method: :delete, data: {confirm: 'Voulez-vous vraiment supprimer cette carte?'}, class: 'btn btn-floating waves-effect waves-light red' %>
                  <%= link_to raw('<i class="material-icons">publish</i>'), new_corridor_path(map), class: 'btn btn-floating waves-effect waves-light green' %>

                </td>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

app/views/upload/new.html.erb
<div class="container">
  <h1 class="center-align thin">Téléverser une carte</h1>

  <%= render 'form' %>

</div>

app/views/upload/new_corridor.html.erb
<div class="container">
  <h1>Téléverser une carte des corridors</h1>

  <%= render 'shared/errors', obj: @map %>

  <div class="card-panel hoverable">
    <div class="row">
      <div class="col s12">
        <%= form_for(@map, url: upload_corridor_path(@map), :action => "upload_corridor", :html => {class: '', role: 'form'}) do |f| %>

            <div class="row">
              <div class="col s12">
                <div class="file-field input-field">
                  <div class="btn waves-effect waves-light"><span>Fichier des corridors</span><%= f.file_field :corridor %></div>
                  <div class="file-path-wrapper"><input class="file-path validate" type="text"></div>
                </div>
              </div>
            </div>

            <%= link_to 'Annuler', upload_index_path, class: 'btn waves-effect waves-light red' %>
            <%= f.submit ('Téléverser'), class: 'btn waves-effect waves-light' %>

        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/upload/upload_corridor.html.erb
<div class="container">
  <h1>Téléverser une carte des corridors</h1>

  <%= render 'shared/errors', obj: @map %>

  <div class="row">
    <div class="col-md-12">
      <%= form_for(@map, url: upload_path(@map), method: :patch, :html => {class: 'form-horizontal', role: 'form'}) do |f| %>

          <div class="row file-field input-field">
            <div class="btn">
              <span>Fichier des corridors</span>
              <%= f.file_field :corridor %>
            </div>
            <div class="file-path-wrapper">
              <input class="file-path validate" type="text">
            </div>
          </div>

          <div class="row">
            <div>
              <%= link_to 'Annuler', upload_index_path, class: 'btn btn-danger btn-sm' %>
              <%= f.submit ('Téléverser'), class: 'btn btn-primary btn-sm' %>
            </div>
          </div>

      <% end %>
    </div>
  </div>

</div>