config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  root 'logins#new'

  resources :admins, except: :show

  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'

  get 'map', to: 'map#display'

  resources :tokens, except: :show

  resources :upload, except: :show
  get '/upload/make_current_map/:id' => 'upload#make_current_map', as: :make_current_map
  get '/upload/corridor/new/:id' => 'upload#new_corridor', as: :new_corridor
  patch '/upload/corridor/:id' => 'upload#upload_corridor', as: :upload_corridor

  resources :classrooms

  namespace :api, defaults: {format: :json} do

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      resources :map, only: [:index, :create]
      get 'map2', to: 'map#map2'

      resources :classrooms, only: [:index, :show]
      get '/classroom/:name', to: 'classrooms#show_by_name'
      get '/classroom_search/:query', to: 'classrooms#search_by_name'

      get '/tags/:id', to: 'tags#get_tags'
      post '/tags/:id', to: 'tags#save_for_classroom'
      delete '/tags/:id', to: 'tags#delete_tag'

      resources :corridors, only: :index
      get '/corridors2', to: 'corridors#corridors2'
      resources :stairs, only: :index
      get '/stair/:name', to: 'stairs#show_by_name'

      get :path, to: 'path#find'

      get :docs, to: 'docs#index'

    end

  end

end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_action :require_admin
  before_action :get_token, only: [:edit, :update, :destroy]

  # GET /tokens

  def index
    @tokens = ApiKey.all
  end

  # POST /tokens

  def create
    @token = ApiKey.new(token_params)
    if @token.save
      flash[:success] = "Le jeton a bien été créé: #{@token.access_token}."
      redirect_to tokens_path
    else
      render 'new'
    end
  end

  # PUT PATCH /token/:id

  def update
    if @token.update(token_params)
      flash[:success] = "Le jeton a bien été modifié."
      redirect_to tokens_path
    else
      render 'edit'
    end
  end

  # DELETE /token/:id

  def destroy
    key_name = @token.name
    @token.destroy
    flash[:danger] = "Le jeton #{key_name} a bien été revoqué."
    redirect_to tokens_path
  end

  # GET /tokens/new

  def new
    @token = ApiKey.new
  end

  # GET /token/:id/edit

  def edit

  end

  private
    def token_params
      params.require(:api_key).permit(:name)
    end

    def get_token
      @token = ApiKey.find(params[:id])
    end

end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/tokens/_form.html.erb
<%= render 'shared/errors', obj: @token %>

<div class="card-panel hoverable">
  <div class="row">
    <div class="col s12">
      <%= form_for(@token, url: tokens_path(@token), :html => {class: 'col s12'}) do |f| %>

          <div class="row">
            <div class="input-field col s12">
              <%= f.text_field :name, class: 'validate', autofocus: true %>
              <label>Nom de la clé</label>
            </div>
          </div>
          <div class="">
            <div class="col s12">
              <%= link_to 'Annuler', tokens_path, class: 'btn waves-effect waves-light red' %>
              <%= f.submit 'Générer', class: 'btn waves-effect waves-light' %>
            </div>
          </div>

      <% end %>
    </div>
  </div>
</div>

app/views/tokens/edit.html.erb
<div class="container">
  <h1 class="center-align thin">Modifier</h1>

  <%= render 'shared/errors', obj: @token %>
  <div class="card-panel hoverable">
    <div class="row">
      <div class="col s12">
        <%= form_for(@token, url: token_path(@token), method: :patch, :html => {class: 'form-horizontal'}) do |f| %>

            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, class: 'validate', autofocus: true %>
                <label>Nom de la clé</label>
              </div>
            </div>
            <div class="">
              <div class="col s12">
                <%= link_to 'Annuler', tokens_path, class: 'btn waves-effect waves-light red' %>
                <%= f.submit 'Modifier', class: 'btn waves-effect waves-light' %>
              </div>
            </div>

        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/tokens/index.html.erb
<div class="row">
  <div class="col s12 m4 l3 fixed-control">

    <div class="card card-top hoverable">
      <div class="card-content">
        <span class="card-title thin">Jetons</span>
        <p>Voici tous les jetons répertoriés On peut les modifier ou les supprimer.</p>
      </div>
      <div class="card-action">
        <%= link_to raw('<i class="material-icons right">add</i>Générer une nouvelle clé'), new_token_path, class: 'btn waves-effect waves-light' %>
      </div>
    </div>

    <div class="side-card">
      <ul class="collapsible hoverable" data-collapsible="expandable">
        <li>
          <div class="collapsible-header">
            <span class="badge"><%= @tokens.count %></span><i class="material-icons">place</i>Jetons
          </div>
        </li>
      </ul>
    </div>
  </div>

  <div class="col s12 m8 l9 offset-m4 offset-l3">
    <div class="card card-top hoverable">
      <div class="card-content no-padding">
        <table class="centered">
          <thead>
          <tr>
            <th>Nom</th>
            <th>Date de création</th>
            <th>Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @tokens.each do |token| %>
              <tr class="table-action table-row">
                <td><%= token.name %></td>
                <td><%= token.created_at %></td>
                <td width="40%">
                  <a class="btn btn-floating waves-effect waves-light waves-circle green" onclick="alert('<%= token.access_token %>')"><i class="material-icons">info_outline</i></a>
                  <%= link_to raw('<i class="material-icons">edit</i>'), edit_token_path(token), class: 'btn btn-floating waves-effect waves-light waves-circle blue' %>
                  <%= link_to raw('<i class="material-icons">delete</i>'), token_path(token), method: :delete, data: {confirm: 'Voulez-vous vraiment supprimer ce jeton?'}, class: 'btn btn-floating waves-effect waves-light red' %>
                </td>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>

</div>

app/views/tokens/new.html.erb
<div class="container">
  <h1 class="center-align thin">Nouveau jeton</h1>

  <%= render 'form' %>

</div>