config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do

  root 'logins#new'

  resources :admins, except: :show

  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'

  get 'map', to: 'map#display'

  resources :tokens, except: :show

  resources :upload, except: :show
  get '/upload/make_current_map/:id' => 'upload#make_current_map', as: :make_current_map
  get '/upload/corridor/new/:id' => 'upload#new_corridor', as: :new_corridor
  patch '/upload/corridor/:id' => 'upload#upload_corridor', as: :upload_corridor

  resources :classrooms

  namespace :api, defaults: {format: :json} do

    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do

      resources :map, only: [:index, :create]
      get 'map2', to: 'map#map2'

      resources :classrooms, only: [:index, :show]
      get '/classroom/:name', to: 'classrooms#show_by_name'
      get '/classroom_search/:query', to: 'classrooms#search_by_name'

      get '/tags/:id', to: 'tags#get_tags'
      post '/tags/:id', to: 'tags#save_for_classroom'
      delete '/tags/:id', to: 'tags#delete_tag'

      resources :corridors, only: :index
      get '/corridors2', to: 'corridors#corridors2'
      resources :stairs, only: :index
      get '/stair/:name', to: 'stairs#show_by_name'

      get :path, to: 'path#find'

      get :docs, to: 'docs#index'

    end

  end

end

app/views/layouts/_messages.html.erb
<div>
  <% flash.each do |name, msg| %>
      <script>
          Materialize.toast('<%= msg %>', 4000, 'toast-<%= name %>')
      </script>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar-fixed">
  <ul id="dropdown-carte" class="dropdown-content">
    <li><%= link_to 'Afficher', map_path %></li>
    <li class="divider"></li>
    <li><%= link_to 'Options', upload_index_path %></li>
  </ul>

  <ul id="dropdown-account" class="dropdown-content">
    <li><%= link_to 'Déconnexion', logout_path, method: :delete %></li>
  </ul>

  <nav class="teal">
    <div class="nav-wrapper">

      <a href="" id="logo" class="brand-logo left bold">GeoApp</a>

      <% if current_admin %>
      <ul id="nav-mobile" class="right hide-on-small-and-down">
        <a class="dropdown-button" href="#" data-activates="dropdown-account"><%= current_admin.username %></a>
      </ul>
      <% end %>

      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li class="<%= 'active' if current_page?(admins_path) %>"><%= link_to 'Administration', admins_path %></li>
        <li class="<%= 'active' if current_page?(tokens_path) %>"><%= link_to 'Jetons', tokens_path %></li>
        <li class="<%= 'active' if current_page?(classrooms_path) %>"><%= link_to 'Locaux', classrooms_path %></li>

        <li class="dropdown <%= 'active' if current_page?(map_path) || current_page?(upload_index_path) %>">
          <a class="dropdown-button" href="#" data-activates="dropdown-carte">Carte</a>
        </li>
        <% if Rails.env.production? %>
            <li><a><%= 'PROD' %></a></li>
        <% elsif Rails.env.development? %>
            <li><a><%= 'DEV' %></a></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeoApi</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body>

    <% if logged_in? %>
        <%= render 'layouts/navigation' %>
    <% end %>

    <%= render 'layouts/messages' %>

    <%= yield %>

  </body>
</html>